### ISSUE TITLE
Crash répété

### ISSUE THREAD

**Issue by nicolasrub** [dwwe2017/voice-server-manager#2]
**Describe the bug**
Bonjour, Avec la licence de 32 Slots inclut avec Teamspeak, tout fonctionne très bien, cependant, avec la licence acheté chez teamspeak directement, l'application crash toutes les 10 à 15 secondes.

**To Reproduce**
Après ajout de la licence Teamspeak, cela fait crash le Teamspeak depuis votre application (licence déjà utilisé sur une ancienne machine et fonctionnelle)

**Expected behavior**
Ne plus avoir de crash

**Screenshots**
https://ibb.co/4tRhjBR

**Desktop (please complete the following information):**
Plesk 18.0.34

**Additional context**
Tout à été dit

**Comment by nicolasrub** [comment]
Pour info, au vu des besoins j'ai acheté la licence, mais si mes autres teamspeak risquent de buguer ainsi et que ce teamspeak n'est aps rapidement réparé je vais devoir annuler l'abonnement

**Comment by dwwe2017** [comment]
Howdy, I'm sorry that I couldn't see that earlier, but currently I don't see how I could help you with the problem? What do the logs say? Have you already activated the debug mode in the Voice Server Manager and checked whether there is an error message? If not, please activate the logs and send them to me. You activate the debug mode using panel.ini, see here: https://github.com/dwwe2017/voice-server-manager/blob/master/panel.ini
